export default {
    TODO_ADD: 'TODO_ADD',
    TODO_REMOVE: 'TODO_REMOVE',
    TODO_UPDATE: 'TODO_UPDATE',
    TODO_TOGGLE: 'TODO_TOGGLE',
    TODO_TOGGLE_ALL: 'TODO_TOGGLE_ALL',
    TODO_CLEAR: 'TODO_CLEAR'
};
